version: '3.9'

services:
  server:
    build: .
    ports:
      - 5000:5000
  
  postgres-db:
    container_name: custom-postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=musics
    ports:
      - 5432:5432
    volumes:
      - pg-data-musics:/var/lib/postgresql/data 

volumes:
  pg-data-musics: